apiVersion: v1
kind: Pod
metadata:
  name: math-pod
spec:
  containers:
  - name: math-add
    image: ubuntu
    command: [ 'expr', '3', '+', '2' ]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never