apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: plmarchino/simple-webapp-color
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
    envFrom:
      - secretRef:
          name: app-secret
    # env:
    #   - name: APP_COLOR
    #     valueFrom:
    #       secretKeyRef:
    #         name: app-secret
    #         key: APP_COLOR
  # volumes:
  #   - name: app-secret-volume
  #     secret:
  #       secretName: app-secret
