apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: mysql
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  subdomain: mysql-h
  hostname: mysql-pod