apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    name: web-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
      - "sleep"
      - "3600"
    serviceAccount: dashboard-sa
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
