apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
  labels:
    name: ubuntu-sleeper
spec:
  containers:
  - name: ubuntu-sleeper
    image: plmarchino/ubuntu-sleeper
    # Arguments for image (same as docker run plmarchino/ubuntu-sleeper 10)
    args: [ "10" ]
    # Entrypoin for image (same as docker run plmarchino/ubuntu-sleeper --entrypoint=sleep2.0)
    # command: ["sleep2.0"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
