apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  containers:
  - name: simple-webapp
    image: simple-webapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /api/ready
        port: 8080
      # tcpSocket:
      #   port: 3306
      # exec:
      #   command:
      #     - cat
      #     - /app/is_ready
      initialDelaySeconds: 20
      periodSeconds: 5
      failureThreshold: 8
