apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    name: web-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
      - "sleep"
      - "3600"
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2
